branches:
  only:
    - master
language: cpp
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: 
            - libstdc++-6-dev

compiler: clang

script:
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uElyas-Crimean:$BINTRAY_API_KEY "https://api.bintray.com/content/elyas-crimean/Elyas-otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
#  provider: script
#  skip-cleanup: true
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x doxydeploy.sh
  - ./doxydeploy.sh
